version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r Lambda/requirements.txt -t lib
  build:
    commands:
      - echo "Building lambda functions"
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - zip -r9 ../deployment_package2.zip .
      - cd ..
      - zip -g deployment_package.zip Search-index.py
      - zip -g deployment_package2.zip index-photos.py
 
