version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r Lambda/requirements.txt -t lib
  build:
    commands:
      - echo "Building lambda functions"
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - zip -g deployment_package.zip Search-index.py
      - zip -g deployment_package1.zip index-photos.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name A2_L2 --zip-file fileb://deployment_package.zip
      - aws lambda update-function-code --function-name A2_L1 --zip-file fileb://deployment_package1.zip
      - echo "DONE!!"
artifacts:
  files:
    - deployment_package.zip
    - deployment_package2.zip
    

