version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r Lambda/requirements.txt -t Lambda/
  build:
    commands:
      - echo "Building lambda functions"
      - cd Lambda && zip -r ../function.zip *
      - cd ..
artifacts:
  files:
    - function.zip
